/* Generated from gap8_perception.output_contract. */
#ifndef GAP8_PERCEPTION_OUTPUT_CONTRACT_H
#define GAP8_PERCEPTION_OUTPUT_CONTRACT_H
#define PERCEPTION_INPUT_WIDTH 160
#define PERCEPTION_INPUT_HEIGHT 120
#define PERCEPTION_SENSOR_CROP_TOP 20
#define PERCEPTION_OUTPUT_CHANNELS 12
#define PERCEPTION_GRID_WIDTH 20
#define PERCEPTION_GRID_HEIGHT 15
#define PERCEPTION_HEATMAP_TL 0
#define PERCEPTION_HEATMAP_TR 1
#define PERCEPTION_HEATMAP_BR 2
#define PERCEPTION_HEATMAP_BL 3
#define PERCEPTION_OFFSET_BASE 4
#define PERCEPTION_CONFIDENCE_BASE 8
#define PERCEPTION_SCORE_LIMIT 6.0f
#define PERCEPTION_CONFIDENCE_THRESHOLD 0.0f
#define PERCEPTION_TERMINAL_SCORE_OFFSET 6.0f
#define PERCEPTION_OFFSET_MIN 0.0f
#define PERCEPTION_OFFSET_MAX 6.0f
#define PERCEPTION_NORMAL_0_DEG -40.0f
#define PERCEPTION_NORMAL_1_DEG -13.333333f
#define PERCEPTION_NORMAL_2_DEG 13.333333f
#define PERCEPTION_NORMAL_3_DEG 40.0f
#endif
